title: Duy Ngoc Lam (Dan Lam) # your name (or website title) here
logo: "/images/LDN.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An Analyst, 
  <br><br>
  A entrepreneur, 
  <br><br>
  is pivoting to CS
  <br><br>
  <a href="https://www.linkedin.com/in/usdanlam/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
